### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lerdmann** [altsan/qe-text-editor#2]
I am using beta version 0.9.6:

first things first: I like it and it does what it promises ! In particular, it can load files where e.exe, e2.exe and epm.exe crash on load.

Here are a couple of suggestions. None of these are critical:
1) I know this editor is not meant to load binary or large (?) files. Doing so nonetheless leads to an exception (not always ...) which is seemingly caught before it hits the OS (which of course is good). I suggest to show a dialog box from the exception handler that the file could not be loaded due to this and that (wrong encoding, out of memory, etc. etc.) ...
2) It would be helpful to load the file from a secondary thread. I currently have to handle a 32 MB text file. While it loads just fine, the application is completely frozen while loading with the main window not repainting.
3) a little more info in the status bar would be helpful, like "loading file ..." and such. Of course that might only work if 2) is in place.

**Comment by altsan** [comment]
I'll consider these, thanks.

**Comment by altsan** [comment]
Hi, would you mind testing with the attached build (OS/2 binary only)?
[qe_os2_097test1.zip](https://github.com/altsan/quick-text-editor/files/2203571/qe_os2_097test1.zip)

File open & save are now done on separate threads, with status display (items 2 and 3).  All operations are super-fast on my SSD drive so it's hard for me to see what genuinely slow operations would be like. (Even a 35MB file takes about 1.5 seconds here.)

Obviously, since this version changes the save logic, only test with backed-up data. :)

Item 1 is tougher.  I assume it's klibc that's intercepting the exceptions, since neither I nor Qt (to my knowledge) add any explicit handlers. I may look at it in the long term, but it's not a short-term project.

**Comment by lerdmann** [comment]
Hi Alex,
this is certainly an improvement. Loading a 78 MB sized text file displays "Opening ....\xul.map (y%)" where y quickly counts up to 99 % (sometimes less than that). While the status bar still refreshes/counts up the percentage loaded I can move around the window.
Then it gets stuck at 99 % (or less, see above, with the vertical scroll bar still inactive) and the window gets frozen/immovable too.
Once the view is completely refreshed the status bar displays "Opened ....\xul.map", the vertical scroll bar becomes active and then I can again move the main window.

So, it looks like not only the file load as such needs its time but also the refresh of the document view which also seems to block the primary thread. While the document view refreshes one CPU core is busy with 100% usage (presumably the CPU executing the primary thread).
Other than that everything is ok, the file loads, I can scroll through the whole file (927786 lines) without any delay, in fact, even dragging the vertical scroll bar slider almost instantaneously refreshes the document view.

Loading a large binary file (like XUL.DLL) still traps the editor (but the error still gets caught and handled by Qt).

**Comment by altsan** [comment]
Regarding the editor refresh, I suspect this is not fixable. In Qt, all UI objects must be on the UI thread, and a quick search seems to suggest this is a known issue when populating very large text documents. I can possibly try to tweak the repainting logic, but I doubt that will help much. (The proper way to handle this would be to split the data to only populate one section of the file at a time, and load other sections on demand; that is far outside the scope of this kind of simple editor, and not something I would consider.)

Do you have word wrap enabled or disabled? I found one remark suggesting that disabling word wrap can improve the editor population efficiency.

I'll tweak the percentage display.

**Comment by lerdmann** [comment]
Ok, I understand that drawing only from the primary thread is a restriction of Qt. Yes, I'd leave it with that.
Just out of curiosity: if a UI object is executing only on the primary thread does this preclude executing drawing code from a secondary thread ? If not it might be possible to send worker messages from the UI Object to some worker Object to do the painting ...

I agree that loading only the visible part of the document is too much effort.

**Comment by altsan** [comment]
All drawing code has to be on the UI thread.

Now, I'm not certain whether the slowdown is in populating the editor document object or in the actual drawing (in other words, the model versus the view). If it's the former, I might be able to experiment with creating the model (QTextDocument) in the worker thread, but I'll have to think about exactly how that would work. (And, of course, there's no guarantee it would.)

**Comment by altsan** [comment]
After looking at this some more, I think the current solution is the best that can be done.
