### ISSUE TITLE
Replace history dropdown does not retain strings of only whitespace

### ISSUE THREAD

**Issue by LewisR** [altsan/qe-text-editor#4]
Testing with 0.9.8, my find history will retain strings consisting of only whitespace (regardless the number of spaces), whereas the dropdown for the replacement seems to discard these.

Example:

    Find: abcde
    
    Replace with:      

(five spaces, to preserve indent). The next time the Replace dialog is opened, the five spaces will not be listed in the replacement history dropdown. However, if the goal is the reverse:

    Find:       
    
    Replace with: abcde

the five spaces are consistently listed in the find history dropdown (as expected).

**Comment by altsan** [comment]
Replacement history was badly broken through version 0.9.8. Please try to reproduce with 0.9.9 when it comes out (or build from latest).

**Comment by LewisR** [comment]
Confirmed fixed in 0.9.9. Thanks.
