### ISSUE TITLE
Add support for marking columns of text

### ISSUE THREAD

**Issue by LewisR** [altsan/qe-text-editor#7]
Currently, block marking is line-based, so beginning to mark a block in a table, for example, will wrap from the starting column to the first column of text on the next line, whether formatted as a table or not. This RFE would allow using a modifier key for the left mouse button to allow marking a particular column (or group of columns) instead of words or lines.

**Comment by altsan** [comment]
I see this as out of scope for a simple-text editor.  It's more appropriate in an advanced or programmer's editor.
