### ISSUE TITLE
When creating a new document, Read-only mode should be unset automatically

### ISSUE THREAD

**Issue by LewisR** [altsan/qe-text-editor#8]
I was reading a document the integrity of which I wanted to ensure, so I set the Read-only option from the menu. When I was done, I wanted to paste clipboard content into the editor to create a new document, so I selected File | New. I was then unable to paste because I was still in Read-only mode.

Suggest that when Read-only mode has been toggled, Ctrl-N (or File | New) should unset Read-only to allow creating a new document.

**Comment by altsan** [comment]
Implemented (with confirmation box).
